### PR TITLE
division by 0

### PR DESCRIPTION
**Pull request by wende**

### CODE REVIEW

**Comment by wende** [comment]
Closes #7

**Comment by fcabouat** [comment]
Hi,

Shouldn't the result of a division by 0 be NaN instead ?
Limit when x > 0, x → 0 of  [ left / x ] = +infinity. But it's only the limit and with x > 0. Since we're often playing with Ints instead of Unsigned Ints, we have 0 == -0, so a number divided by zero would be both equal to +infinity and -infinity, which is a bit weird mathematically...

Cheers,

François

**Comment by wende** [comment]
@fcabouat 
Hi Francois,

Thank you for your interest! In terms of the results of mathematical operators we want to be 100% consistent with how Elm does it.

It's all work in progress since you still can't use math operators on `infinity`.
But the target right now is to mimic Elm

screen shot 2017-12-27 at 20 29 15

**Comment by fcabouat** [comment]
Hi,

I get the idea of strictly following Elm here, so I'll report it upstream.

I think the problem is best summarized by this statement from Elm repl :
> -1 / 0 == 1 / -0
False : Bool

cheers,

**Pull request merged**
